baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '5idereal'
theme = 'gallery'
timeout = '600s'

[params]
  title = "5idereal"
  description = "巴拉巴拉"
  defaultTheme = "dark"

[author]
  name = "Enfeng Tsao"