languageCode = 'zh-tw'
timezone = 'Asia/Taipei'
title = '5idereal'
theme = 'gallery'
timeout = '1800s'
copyright = "© Enfeng Tsao"

[params]
  title = "5idereal"
  description = ""
  defaultTheme = "dark"
  [params.author]
    email = "contact@5idereal.cc"
    name = "Enfeng Tsao"
  [params.socialIcons]
    facebook = "https://www.facebook.com/5idereal"
    instagram = "https://www.instagram.com/enfeng_tsao"
    github = "https://github.com/5idereal"
    youtube = "https://www.youtube.com/5idereal"
    email = "mailto:contact@5idereal.cc"