languageCode = 'zh-tw'
timezone = 'Asia/Taipei'
title = '5idereal'
theme = 'gallery'
timeout = '1800s'
copyright = "© Enfeng Tsao"

[params]
  title = "5idereal"
  description = ""
  defaultTheme = "dark"

[author]
  name = "Enfeng Tsao"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/5idereal"
    weight = 3